# Generated by Django 2.1.1 on 2018-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180923_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(blank=True, null=True, to='polls.GameMode', verbose_name='available game modes'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='release date of the game'),
        ),
    ]
