# Generated by Django 2.1.1 on 2018-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180927_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(blank=True, to='polls.GameMode', verbose_name='available game modes'),
        ),
    ]
