# Generated by Django 2.1.1 on 2018-09-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180927_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='country of origin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Brand of equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Equipment manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name of the game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='game publisher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='acronym',
            field=models.CharField(blank=True, default='', help_text='Game genre acronym', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of genre', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='country of birth'),
            preserve_default=False,
        ),
    ]
