# Generated by Django 2.1.1 on 2018-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180927_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='game image url'),
        ),
    ]
