# Generated by Django 2.1.1 on 2018-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clan_pendings',
            field=models.ManyToManyField(related_name='clan_pendings', to='leagues.Clan'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_pendings',
            field=models.ManyToManyField(related_name='team_pendings', to='leagues.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='clans',
            field=models.ManyToManyField(related_name='clan_member', to='leagues.Clan', verbose_name='Clan memberships'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='team_member', to='leagues.Team', verbose_name='Team memberships'),
        ),
    ]
