# Generated by Django 2.1.1 on 2018-10-04 09:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country of birth'),
        ),
    ]
