# Generated by Django 2.1.1 on 2018-10-04 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20181004_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='description',
            field=models.TextField(blank=True, help_text='Description of clan', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Description of team', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, help_text='Description of tournament', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country of origin'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
