# Generated by Django 2.1.1 on 2018-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20181002_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Description of genre', verbose_name='description'),
        ),
    ]
