# Generated by Django 2.1.1 on 2018-10-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.Player', verbose_name='Leader of the clan'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.Player', verbose_name='Leader of the team'),
        ),
    ]
