# Generated by Django 2.1.1 on 2018-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_merge_20181006_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clans',
            field=models.ManyToManyField(related_name='clan_members', to='leagues.Clan', verbose_name='Clan memberships'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='team_members', to='leagues.Team', verbose_name='Team memberships'),
        ),
    ]
