# Generated by Django 2.1.1 on 2018-11-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20181006_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_won', models.BooleanField(verbose_name='game won')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.Match')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.ManyToManyField(through='leagues.PlayedMatch', to='leagues.Match', verbose_name='Played matches'),
        ),
        migrations.AddField(
            model_name='playedmatch',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='playedmatch',
            unique_together={('player', 'match')},
        ),
    ]
