# Generated by Django 2.1.1 on 2018-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20181110_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
