# Generated by Django 2.1.1 on 2018-11-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_auto_20181111_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='beginning',
        ),
    ]
