# Generated by Django 2.1.1 on 2018-11-13 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_remove_match_beginning'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='beginning',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='beginning of the match'),
        ),
    ]
