# Generated by Django 2.1.1 on 2018-11-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_playedmatch_clan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='clans',
        ),
        migrations.AddField(
            model_name='player',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_member', to='leagues.Clan', verbose_name='Clan membership'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_leader', to='leagues.Player', verbose_name='Leader of the clan'),
        ),
    ]
