# Generated by Django 2.1.1 on 2018-11-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20181116_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clan_members', to='leagues.Clan', verbose_name='Clan membership'),
        ),
    ]
