# Generated by Django 2.1.1 on 2018-11-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_tournament_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(through='leagues.RegisteredTeams', to='leagues.Tournament', verbose_name='Registered tournaments'),
        ),
    ]
