# Generated by Django 2.1.1 on 2018-11-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_auto_20181118_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leagues.Game', verbose_name='related game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leagues.GameMode', verbose_name='game mode of the match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_a', to='leagues.Team', verbose_name='first participating team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_b', to='leagues.Team', verbose_name='second participating team'),
        ),
    ]
