# Generated by Django 2.1.1 on 2018-11-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_auto_20181118_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='leagues.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_mode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='leagues.GameMode'),
            preserve_default=False,
        ),
    ]
