# Generated by Django 2.1.1 on 2018-11-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_match_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='done',
        ),
    ]
