# Generated by Django 2.1.1 on 2018-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0024_remove_match_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
