# Generated by Django 2.1.1 on 2018-11-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0025_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredteams',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='leagues.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
