# Generated by Django 2.1.1 on 2018-11-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0026_auto_20181119_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredteams',
            name='game',
        ),
    ]
