# Generated by Django 2.1.1 on 2018-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0027_remove_registeredteams_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='active',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(to='leagues.GameMode', verbose_name='available game modes'),
        ),
    ]
