# Generated by Django 2.1.1 on 2018-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_auto_20181120_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
