# Generated by Django 2.1.1 on 2018-11-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_auto_20181120_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='leagues.Genre', verbose_name='genre of the game'),
            preserve_default=False,
        ),
    ]
