# Generated by Django 2.1.1 on 2018-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0030_gamemode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(blank=True, to='leagues.GameMode', verbose_name='available game modes'),
        ),
    ]
