# Generated by Django 2.1.1 on 2018-11-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0030_auto_20181121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_mode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='leagues.GameMode', verbose_name='game mode of the match'),
            preserve_default=False,
        ),
    ]
