# Generated by Django 2.1.1 on 2018-11-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0031_auto_20181121_1334'),
        ('leagues', '0031_auto_20181121_1513'),
    ]

    operations = [
    ]
