# Generated by Django 2.1.1 on 2018-11-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0032_merge_20181121_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='match_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(to='leagues.GameMode', verbose_name='available game modes'),
        ),
    ]
