# Generated by Django 2.1.1 on 2018-11-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0033_auto_20181122_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='games',
        ),
    ]
