# Generated by Django 2.1.1 on 2018-11-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0035_auto_20181125_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='clan_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='leagues.Clan'),
        ),
    ]
