# Generated by Django 2.1.1 on 2018-11-26 10:51

from django.db import migrations, models
import leagues.models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0036_match_clan_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='opening_date',
            field=models.DateField(default=leagues.models.begin_date_default, verbose_name='date of the tournament start'),
        ),
    ]
