# Generated by Django 2.1.1 on 2018-11-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0038_team_clan_pendings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='clan_pendings',
        ),
        migrations.AddField(
            model_name='team',
            name='clan_pending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_request', to='leagues.Clan'),
        ),
    ]
